

// constants/fetalSizeData.ts

export type Trimester = "Primer trimestre" | "Segundo trimestre" | "Tercer trimestre";

export interface FetalWeekData {
  week: number;
  fruit: string;
  emoji: string;
  lengthCm: number;
  weightG: number;
  desarrollo: string;
  cambios: string;
}

export function getTrimester(week: number): Trimester {
  if (week <= 13) return "Primer trimestre";
  if (week <= 27) return "Segundo trimestre";
  return "Tercer trimestre";
}

export const FETAL_SIZE_DATA: FetalWeekData[] = [
  {
    week: 4,
    fruit: "Semilla de amapola",
    emoji: "🌱",
    lengthCm: 0.2,
    weightG: 0.1,
    desarrollo: "El embrión recién se está implantando y empiezan a formarse las capas que darán origen a todos los órganos.",
    cambios: "Es posible que todavía no notes ningún síntoma, aunque el cuerpo ya empezó a producir la hormona del embarazo.",
  },
  {
    week: 5,
    fruit: "Semilla de sésamo",
    emoji: "🌰",
    lengthCm: 0.3,
    weightG: 0.2,
    desarrollo: "Comienza a formarse el tubo neural, que luego dará origen al cerebro y a la médula espinal.",
    cambios: "Pueden aparecer los primeros síntomas: cansancio, sensibilidad en los pechos o necesidad de orinar más seguido.",
  },
  {
    week: 6,
    fruit: "Lenteja",
    emoji: "🫘",
    lengthCm: 0.6,
    weightG: 0.5,
    desarrollo: "El corazón ya late y empiezan a esbozarse los brotes de brazos y piernas.",
    cambios: "Las náuseas matutinas suelen aparecer por estas semanas, junto con cambios en el olfato.",
  },
  {
    week: 7,
    fruit: "Arándano",
    emoji: "🫐",
    lengthCm: 1.3,
    weightG: 1,
    desarrollo: "El cerebro se desarrolla rápidamente y ya se distinguen las fosas nasales, la boca y las orejas en formación.",
    cambios: "El cansancio y las náuseas pueden intensificarse a medida que suben los niveles hormonales.",
  },
  {
    week: 8,
    fruit: "Frambuesa",
    emoji: "🍇",
    lengthCm: 1.6,
    weightG: 1,
    desarrollo: "Los dedos de manos y pies comienzan a formarse, aunque todavía están unidos por una membrana.",
    cambios: "La ropa puede empezar a sentirse un poco más ajustada en la cintura, aunque la panza todavía no se nota.",
  },
  {
    week: 9,
    fruit: "Uva",
    emoji: "🍇",
    lengthCm: 2.3,
    weightG: 2,
    desarrollo: "El embrión ya se mueve, aunque todavía no se siente, y los párpados empiezan a cubrir los ojos.",
    cambios: "Los pechos pueden seguir sensibles y es común notar más venas visibles en ellos.",
  },
  {
    week: 10,
    fruit: "Kumquat",
    emoji: "🍊",
    lengthCm: 3.1,
    weightG: 4,
    desarrollo: "Todos los órganos vitales ya se formaron y a partir de ahora se dedicarán a crecer y madurar.",
    cambios: "Las náuseas suelen empezar a ceder de a poco para algunas personas, aunque para otras continúan.",
  },
  {
    week: 11,
    fruit: "Higo",
    emoji: "🫒",
    lengthCm: 4.1,
    weightG: 7,
    desarrollo: "La cabeza representa casi la mitad del tamaño total, y ya se pueden distinguir los deditos de manos y pies.",
    cambios: "Puede empezar a notarse un leve abultamiento en el abdomen bajo.",
  },
  {
    week: 12,
    fruit: "Lima",
    emoji: "🍋",
    lengthCm: 5.4,
    weightG: 14,
    desarrollo: "Los reflejos comienzan a aparecer: los deditos pueden abrirse y cerrarse.",
    cambios: "El riesgo de pérdida disminuye notablemente a partir de esta semana, lo que suele traer algo de alivio.",
  },
  {
    week: 13,
    fruit: "Vaina de arvejas",
    emoji: "🫛",
    lengthCm: 7.4,
    weightG: 23,
    desarrollo: "Las huellas digitales ya están formadas y los intestinos, que se desarrollaron fuera del cuerpo, se ubican en su lugar definitivo.",
    cambios: "Termina el primer trimestre; para muchas personas los síntomas empiezan a suavizarse a partir de aquí.",
  },
  {
    week: 14,
    fruit: "Durazno",
    emoji: "🍑",
    lengthCm: 8.7,
    weightG: 43,
    desarrollo: "Comienza a producir orina y ya se distinguen las expresiones faciales, como fruncir el ceño.",
    cambios: "Es habitual sentir un salto de energía al entrar en el segundo trimestre.",
  },
  {
    week: 15,
    fruit: "Manzana",
    emoji: "🍎",
    lengthCm: 10.1,
    weightG: 70,
    desarrollo: "Puede empezar a percibir la luz, aunque los párpados sigan cerrados, y los huesos siguen endureciéndose.",
    cambios: "Puede aparecer más apetito a medida que las náuseas quedan atrás.",
  },
  {
    week: 16,
    fruit: "Aguacate",
    emoji: "🥑",
    lengthCm: 11.6,
    weightG: 100,
    desarrollo: "El oído sigue desarrollándose y podría empezar a percibir sonidos apagados, incluida tu voz.",
    cambios: "Es posible que sientas los primeros movimientos leves, como pequeñas burbujas.",
  },
  {
    week: 17,
    fruit: "Nabo",
    emoji: "🥔",
    lengthCm: 13,
    weightG: 140,
    desarrollo: "Empieza a acumular grasa corporal y el cordón umbilical se vuelve más grueso y fuerte.",
    cambios: "El centro de gravedad va cambiando de a poco, por lo que conviene cuidar el equilibrio.",
  },
  {
    week: 18,
    fruit: "Pimiento morrón",
    emoji: "🫑",
    lengthCm: 14.2,
    weightG: 190,
    desarrollo: "Los oídos ya están en su posición final y puede empezar a bostezar e hipar.",
    cambios: "Si es tu primer embarazo, es un momento común para empezar a notar los movimientos fetales.",
  },
  {
    week: 19,
    fruit: "Tomate grande",
    emoji: "🍅",
    lengthCm: 15.3,
    weightG: 240,
    desarrollo: "Se forma una capa protectora en la piel (vérnix caseosa) que la resguarda del líquido amniótico.",
    cambios: "Pueden aparecer molestias en la zona lumbar a medida que la postura se va ajustando.",
  },
  {
    week: 20,
    fruit: "Banana",
    emoji: "🍌",
    lengthCm: 25.6,
    weightG: 300,
    desarrollo: "Llegaste a la mitad del embarazo. El bebé traga líquido amniótico regularmente, lo que ayuda a su sistema digestivo.",
    cambios: "Es el momento típico de la ecografía morfológica, donde se revisa el desarrollo de los órganos.",
  },
  {
    week: 21,
    fruit: "Zanahoria",
    emoji: "🥕",
    lengthCm: 26.7,
    weightG: 360,
    desarrollo: "Las cejas y los párpados están completamente formados y los movimientos se sienten con más claridad.",
    cambios: "El apetito suele aumentar de forma notoria durante estas semanas.",
  },
  {
    week: 22,
    fruit: "Papaya pequeña",
    emoji: "🥭",
    lengthCm: 27.8,
    weightG: 430,
    desarrollo: "Los labios, párpados y cejas se ven cada vez más definidos, y ya distingue tu voz de otros sonidos.",
    cambios: "Pueden aparecer estrías a medida que la piel del abdomen se estira.",
  },
  {
    week: 23,
    fruit: "Mango grande",
    emoji: "🥭",
    lengthCm: 28.9,
    weightG: 501,
    desarrollo: "La piel todavía es fina y translúcida, y se empiezan a marcar las líneas de las palmas de las manos.",
    cambios: "Los movimientos se pueden sentir desde afuera si apoyás la mano sobre el abdomen.",
  },
  {
    week: 24,
    fruit: "Choclo",
    emoji: "🌽",
    lengthCm: 30,
    weightG: 600,
    desarrollo: "Los pulmones siguen madurando y desarrollando las estructuras necesarias para respirar aire.",
    cambios: "Es habitual que se indique el análisis de tolerancia a la glucosa alrededor de esta semana.",
  },
  {
    week: 25,
    fruit: "Rutabaga",
    emoji: "🥔",
    lengthCm: 34.6,
    weightG: 660,
    desarrollo: "Empieza a acumular más grasa bajo la piel, lo que suaviza sus rasgos y le da forma más redondeada.",
    cambios: "Pueden aparecer calambres en las piernas, sobre todo durante la noche.",
  },
  {
    week: 26,
    fruit: "Lechuga",
    emoji: "🥬",
    lengthCm: 35.6,
    weightG: 760,
    desarrollo: "Los ojos empiezan a abrirse por primera vez y responde a estímulos de luz y sonido.",
    cambios: "La falta de aire leve es frecuente a medida que el útero presiona el diafragma.",
  },
  {
    week: 27,
    fruit: "Brócoli",
    emoji: "🥦",
    lengthCm: 36.6,
    weightG: 875,
    desarrollo: "El cerebro crece rápidamente y su sistema inmunológico se fortalece con tus anticuerpos.",
    cambios: "Puede tocarte la prueba de tolerancia a la glucosa, si tu médico la programó.",
  },
  {
    week: 28,
    fruit: "Berenjena",
    emoji: "🍆",
    lengthCm: 37.6,
    weightG: 1005,
    desarrollo: "Empieza el tercer trimestre. Los párpados ya se abren y cierran, y las pestañas están completamente formadas.",
    cambios: "Las visitas al control prenatal suelen volverse más seguidas a partir de esta etapa.",
  },
  {
    week: 29,
    fruit: "Calabaza butternut",
    emoji: "🎃",
    lengthCm: 38.6,
    weightG: 1153,
    desarrollo: "Los músculos y pulmones siguen madurando, y la cabeza crece para acompañar el desarrollo del cerebro.",
    cambios: "El cansancio puede volver a aumentar a medida que el cuerpo carga más peso.",
  },
  {
    week: 30,
    fruit: "Repollo",
    emoji: "🥬",
    lengthCm: 39.9,
    weightG: 1319,
    desarrollo: "La médula ósea ya produce glóbulos rojos por sí sola, sin depender de otros órganos.",
    cambios: "Es común sentir contracciones leves e irregulares (de entrenamiento) durante el día.",
  },
  {
    week: 31,
    fruit: "Coco",
    emoji: "🥥",
    lengthCm: 41.1,
    weightG: 1502,
    desarrollo: "Los cinco sentidos ya están funcionando y el sistema nervioso central sigue madurando.",
    cambios: "Dormir cómoda puede volverse más difícil por el tamaño del abdomen.",
  },
  {
    week: 32,
    fruit: "Jícama",
    emoji: "🥔",
    lengthCm: 42.4,
    weightG: 1702,
    desarrollo: "Las uñas ya llegan a la punta de los dedos y practica movimientos de respiración con líquido amniótico.",
    cambios: "La hinchazón leve en pies y tobillos es frecuente hacia el final del día.",
  },
  {
    week: 33,
    fruit: "Ananá",
    emoji: "🍍",
    lengthCm: 43.7,
    weightG: 1918,
    desarrollo: "Los huesos del cráneo todavía son blandos y flexibles, lo que facilita el paso por el canal de parto.",
    cambios: "Pueden aparecer más contracciones de entrenamiento a medida que el cuerpo se prepara.",
  },
  {
    week: 34,
    fruit: "Melón cantaloupe",
    emoji: "🍈",
    lengthCm: 45,
    weightG: 2146,
    desarrollo: "El sistema nervioso central y los pulmones siguen madurando de cara al nacimiento.",
    cambios: "El espacio se reduce, por lo que los movimientos pueden sentirse distintos: más lentos pero más marcados.",
  },
  {
    week: 35,
    fruit: "Melón honeydew",
    emoji: "🍈",
    lengthCm: 46.2,
    weightG: 2383,
    desarrollo: "Los riñones ya están completamente desarrollados y el hígado empieza a procesar algunos desechos.",
    cambios: "Las visitas al baño suelen volverse más frecuentes por la presión sobre la vejiga.",
  },
  {
    week: 36,
    fruit: "Lechuga romana",
    emoji: "🥬",
    lengthCm: 47.4,
    weightG: 2622,
    desarrollo: "La capa protectora de vérnix empieza a desprenderse y suele acomodarse con la cabeza hacia abajo.",
    cambios: "La falta de aire puede aliviarse si el bebé desciende hacia la pelvis.",
  },
  {
    week: 37,
    fruit: "Acelga (atado)",
    emoji: "🥬",
    lengthCm: 48.6,
    weightG: 2859,
    desarrollo: "Se considera prematuro tardío. Sigue ganando peso y madurando sus pulmones día a día.",
    cambios: "Pueden empezar a notarse señales de que el parto se acerca, como más presión pélvica.",
  },
  {
    week: 38,
    fruit: "Puerro",
    emoji: "🧅",
    lengthCm: 49.8,
    weightG: 3083,
    desarrollo: "Los órganos ya están listos para funcionar fuera del útero, incluidos los pulmones.",
    cambios: "El cuello uterino puede empezar a prepararse de a poco para el trabajo de parto.",
  },
  {
    week: 39,
    fruit: "Sandía pequeña",
    emoji: "🍉",
    lengthCm: 50.7,
    weightG: 3288,
    desarrollo: "Se considera a término. Sigue acumulando grasa que lo ayudará a regular la temperatura al nacer.",
    cambios: "Cualquier día podría comenzar el trabajo de parto; conviene tener todo listo.",
  },
  {
    week: 40,
    fruit: "Sandía",
    emoji: "🍉",
    lengthCm: 51.2,
    weightG: 3462,
    desarrollo: "El desarrollo se completó. Solo falta que decida cuándo llegar al mundo.",
    cambios: "La fecha probable de parto llegó; el nacimiento puede darse antes o después de esta semana.",
  },
];

export function getFetalWeekData(week: number): FetalWeekData {
  const clamped = Math.min(Math.max(week, 4), 40);
  return FETAL_SIZE_DATA.find((d) => d.week === clamped) ?? FETAL_SIZE_DATA[0];
}
